version: '2'
services:
  app:
    build:
      context: ${APP_LOCAL}
      args:
        APP_PATH: ${APP_PATH}
    command: [yarn, start]
    env_file:
      - '.env'
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ${APP_LOCAL}:${APP_PATH}
      - ${APP_PATH}/node_modules
  server:
    build:
      context: ${SERVER_LOCAL}
      args:
        APP_PATH: ${APP_PATH}
    command: [yarn, start]
    env_file:
      - '.env'
    ports:
      - '${SERVER_PORT}:3000'
    volumes:
      - ${SERVER_LOCAL}:${APP_PATH}
      - ${APP_PATH}/node_modules
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - /var/lib/mysql
    env_file:
      - '.env'
    ports:
      - '${MYSQL_PORT}:3306'
