export const ROLE = {
  USER: 'USER',
  MONITOR: 'MONITOR',
  ACCOUNTANT: 'ACCOUNTANT',
  EDITOR: 'EDITOR',
  MANAGER: 'MANAGER'
}

export const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  RESERVED: 'RESERVED',
  WAITING: 'WAITING',
  ACCEPTED: 'ACCEPTED',
  STANDBY: 'STANDBY',
  DELIVERING: 'DELIVERING',
  ARCHIEVED: 'ARCHIEVED',
  CANCELED: 'CANCELED'
}
